title = "Daniel Iong"
baseURL = "http://www.danieliong.me/"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = true
canonifyURLs = true

[params]
# address = "Ann Arbor, MI"
email = "daniong@umich.edu"
favicon = "/favicon.ico"
firstName = "Daniel"
lastName = "Iong"
phone = "510-816-8686"
profileImage = "img/grad_pic.jpg"
showEducation = true
showExperience = false
showOpenSource = false
showProjects = false
showPublications = true
showQr = false
showSkills = true
showBlog = true
showSoftware = true
showTeaching = true

[params.google.analytics]
trackerID = "UA-175735513-1"

[[params.handles]]
link = "https://www.linkedin.com/in/danieliong/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/danieliong/"
name = "GitHub"

[[params.handles]]
link="https://www.facebook.com/daniel.iong/"
name="Facebook"

[[params.handles]]
link="https://www.instagram.com/danieliongg/"
name="Instagram"

[[params.handles]]
link="https://twitter.com/IongDaniel"
name="Twitter"

[[params.handles]]
link="https://scholar.google.com/citations?user=b6dIhg8AAAAJ&hl=en"
name="Google Scholar"

# [[params.handles]]
# link = "https://bitbucket.org/eddiewebb/"
# name = "Bitbucket"

# [[params.handles]]
# link = "https://stackoverflow.com/users/story/82880"
# name = "Stack Overflow"

# [[params.handles]]
# link = "https://keybase.io/edwardawebb"
# name = "Keybase"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"